### ISSUE TITLE
commit change后github Pages网站没有发生变化

### ISSUE THREAD

**Issue by AlexanderChen-Real** [NewFuture/CV#4]
fork后自动生成了github Pages网站，之后修改resume文件，Pages网站没有发生变化。请问是可以多次commit change并且自动编译github Pages吗，还是只能一次commit change，然后github Pages会固定不变

**Comment by NewFuture** [comment]
gh pages再push后会自动build的
可以看一看是否是build fail了，
通常是yml格式有问题

**Comment by butaileng** [comment]
我自建分支之后，修改resume.yaml文件之后，commit没反应了啊，是不是有问题哦。yml格式也检测了没问题。比如我的GitHub账号是aaa   分支是bbb   那预览的地址是什么

**Comment by NewFuture** [comment]
分支默认还是 `gh-pages` 其它分支默认不会生成
