### ISSUE TITLE
已经存在github托管个人博客时页面不存在

### ISSUE THREAD

**Issue by innovatedmonster** [NewFuture/CV#6]
按照用法去做了，但是输入地址发现页面不存在，请问是不是和个人博客地址冲突的原因？（以前我搭的github博客和本项目的地址一模一样）

**Comment by shesbeendead** [comment]
好像需要将仓库设置为public，且配置github pages

**Comment by NewFuture** [comment]
和仓库名一样: https://innovatedmonster.github.io/myResume/
